### ISSUE TITLE
structure of the library

### ISSUE THREAD

**Issue by lucasrodes** [owid/data-utils-py#2]
As per discussions with @pabloarosado, the library should have individual submodules for each "category". Some categories that we have identified can be:

- `io`: Input/output file management. May include local and remote files (Google Drive, S3, etc.)?
- `checks`: Checks on the data.
- `clean`: Cleaning of the data.

etc.

This is open for discussion.

**Comment by pabloarosado** [comment]
@Marigold @lucasrodes what about the following structure?
* `common`: Common objects that will be shared by other modules, possibly definitions of shared global constants.
* `dataframes`: Related to operations with dataframes (not necessarily owid-related things). I'm not totally sure about the name, I thought we could call it `df`, but that could be problematic, since `df` is often used for the actual dataframe object.
* `io`: Related to reading/writing. For example, `read_json`, `write_json`. We could move the S3 object here, but maybe we should avoid making this module too big.
* `s3`: Related to reading/writing to S3.
* `gdrive`: Related to reading/writing to Google Drive (I don't have any functions on this, but Lucas mentioned it).
* `population`: Standardization of countries/regions, adding region aggregations, listing countries in a region, etc. This would be very specific for owid needs (in contrast with the previous modules that are more generic). We have discussed a few times whether this should be part of `etl`, but `etl` is going to be a massive repos at some point, so (1) it would be problematic to import it in other repos, and (2) it seems like a good idea to take code out of `etl` that can be considered independent and generic.
* `checks`: Related to sanity checks. Again, very specific to owid needs. This includes checks on a single dataset (whether countries are standardized, whether values are in reasonable ranges, etc.) and checks on pairs of dataset (e.g. an old and new version of a dataset). I thought that the `dataframes.compare` could be part of it, but I suppose it's more convenient if the sanity checks import `dataframes.compare`.

Do you agree on the names and the logic? And what other modules do you think may be missing (for example, Lucas mentioned `clean`, what would that one have)?

**Comment by lucasrodes** [comment]
Nice! Thanks for your proposal @pabloarosado. I think these modules would be great. 

I probably only have some doubts about the name for `population`, as - from what I understand - it would have logic that would not necessarily imply population. Maybe using `regions` instead?

As per the `clean` module (or similar name), we currently have a [cleaning module](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/utils/clean) for the covid project. In it, we have e.g.:

- Clean numeric values: From a comma-separated string value ("120,000.00") to an integer (120000). [[source code](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/utils/clean/numbers.py)].
- Standardise date formats (YYYY-MM-DD), etc. [[source code](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/utils/clean/dates.py)]
- Cleaning texts, e.g. working with encodings. [[source code](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/utils/clean/strings.py)].
- Cleaning some URLs, e.g. more friendly URLs. [[source code](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/utils/clean/urls.py)]

Perhaps a better naming is `format`?

**Comment by pabloarosado** [comment]
Thanks @lucasrodes:
* `population` -> `region`. I agree that `population` is not a great name. I'm not sure if `regions` would be. Maybe `geo`, given that it's related to geographical entities? This would make sense if we consider that the regions functions can become more complex in the future, if we start considering time-dependent country boundaries and such things.
* I prefer `format` instead of `clean`.
* I agree that io should become a folder containing `s3`, `gdrive`, etc.
